name: Danger Checks

# This will cancel any in progress workflows for the same PR, if
# multiple pushes happen in quick succession.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request_target:
    types: [ opened, synchronize, reopened ]
    branches: [ kmp, android_version ]

jobs:
  danger:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version-file: .github/.java-version

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Danger Checks
        uses: danger/kotlin@1.3.2
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}